Miles Maurizio \ \ 09/23/25 

#set text(top-edge: 0.7em, bottom-edge: -0.3em) 

#set par(leading: 1em)

#set par(first-line-indent: (amount: 2em, all: true))

\ \

Inclusivity is something all companies struggle to fully capture, with recent pull-backs on protections for social minorities and diverse groups lately. Ryan J. Phillips' article, "Queering the Audience Commodity: Political Economy and the Articulation of Desire in NHL Pride Nights" tackles this issue and how it ties with the audience commodity concept. This is specifically talked about in reference to the NHL, or National Hockey League, and how it has handled diversity and what audiences they choose to target as a major sports league.

The audience commodity concept speaks on how in broadcast media, the product being sold is the audience themselves and their attention. This means companies value the majority being targeted more, as it is more profitable than targeting a smaller demographic of people. Historically, advertisers and broadcasters have prioritized male audiences over female audiences (Phillips 2). This means that minorities attention is often treated as less valuable, and that catering to their opinions, especially if they go against the majorities, is seen as unprofitable. For example, advertisers selling beer will target white men on average, seeing as they are the primary target for the product. That company may be willing to cut their sales with women as long as it boosts their sales with men, seeing it as more profitable. This also means that companies catered to stigmatised minority groups, like the queer community, often struggle to gain that majority audiences' attention and are less profitable in sales and business than companies that cater to sexually conformist communities.

In 2023, Philadelphia Flyers player Ivan Provorov refused to wear a pride jersey on religious grounds, which sparked controversy and a short lived ban on pride jerseys and apparel being worn which only ended after mass protest. Media coverage on the situation showed how the NHL actively favoured the majority of their fans over their image to people in the queer community. Their corporate image meant more to them than inclusivity, and their choice to switch back only after backlash reflects that. Travis Dermott, a player on the late Arizona Coyotes team, openly protested the ban on pride apparel and played with rainbow tape on his stick (Phillips 9). He was in a very vulnerable position due to his short-term contract and being on a struggling team which was later moved to Utah. Queer members of the hockey community spoke out about their disappointment with this ban, and stood with Dermott in calling out their behaviour against Pride Night and other events supporting the queer community. Phillips speaks on specific interactions between the communities, and targets how queer communities are generally seen as a less important demographic than traditionally conservative communities. They also speak on how certain teams, and the NHL as a whole, treat Pride Night as a tolerant event, not a fully proud one, similar to many other companies in the past. This phenomenon is commonly referred to as rainbow-washing, and most obviously seen in companies catering to queer communities during June, while instantly cutting off that support come July. Phillips does a good job at tying all of these concepts together, and explaining the situation at hand for individuals who may not be as well-versed in the hockey community.

Audience commodity is a concept that, while I wasn't fully aware of until reading Phillips' article, is all around us. Understanding how it affects society and its view on minorities affected by it is important, especially when talking about communication between corporations and their audiences. While I was a bystander during this event, and stood with Dermott during his protest, analysing it under a lens like this gives me a lot more understanding and has made me think harder about my favourite team's role as an ally in situations like these.
